

services:
  db:
    image: postgres:15
    container_name: moneytransfer-db
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: .      # Root folder of Spring Boot
      dockerfile: Dockerfile
    container_name: moneytransfer-app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./money-transfer-frontend   # Angular folder
      dockerfile: Dockerfile
    container_name: moneytransfer-frontend
    ports:
      - "4200:80"  # Nginx exposes port 80 inside container
    depends_on:
      - backend

volumes:
  db-data:
